import Testing
@testable import VoxCore

@Suite("RewriteOutputContract")
struct RewriteOutputContractTests {

    // MARK: - Accepted (clean output)

    @Test("Clean text with no violations passes")
    func cleanTextAccepted() {
        let output = "I went to the store and bought some groceries."
        let verdict = RewriteOutputContract.validate(output, level: .clean)
        #expect(verdict == .accepted(output))
    }

    @Test("Polish text with no violations passes")
    func polishTextAccepted() {
        let output = "The meeting concluded with three action items."
        let verdict = RewriteOutputContract.validate(output, level: .polish)
        #expect(verdict == .accepted(output))
    }

    @Test("Raw level always passes without validation")
    func rawLevelBypasses() {
        let output = "Here's the cleaned version of your text."
        let verdict = RewriteOutputContract.validate(output, level: .raw)
        #expect(verdict == .accepted(output))
    }

    // MARK: - Preamble detection

    @Test("Detects 'Here's the cleaned' preamble", arguments: [
        "Here's the cleaned version:\nI went to the store.",
        "here's the cleaned text:\nI went to the store.",
        "Here's the polished version:\nI went to the store.",
    ])
    func detectsHeresPreamble(input: String) {
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "I went to the store.")
        #expect(violations.count == 1)
        guard case .preamble = violations[0] else {
            Issue.record("Expected preamble violation")
            return
        }
    }

    @Test("Detects 'Sure,' preamble")
    func detectsSurePreamble() {
        let input = "Sure, here you go:\nThe quick brown fox."
        let verdict = RewriteOutputContract.validate(input, level: .polish)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "The quick brown fox.")
        #expect(violations.contains(where: { if case .preamble = $0 { return true }; return false }))
    }

    @Test("Detects 'Of course!' preamble")
    func detectsOfCoursePreamble() {
        let input = "Of course! Here is the text:\nSome actual content here."
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(let text, _) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        // "Of course!" line removed; "Here is the text:" stays since we only strip first preamble line
        #expect(text.contains("Some actual content here."))
    }

    // MARK: - Attribution detection (fixes #319)

    @Test("Detects 'Transcribed by otter.ai' attribution")
    func detectsOtterAttribution() {
        let input = "I went to the store and bought some groceries.\n\nTranscribed by otter.ai"
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "I went to the store and bought some groceries.")
        #expect(violations.count == 1)
        guard case .attribution = violations[0] else {
            Issue.record("Expected attribution violation")
            return
        }
    }

    @Test("Detects 'Transcribed by Rev' attribution")
    func detectsRevAttribution() {
        let input = "Meeting notes from today.\nTranscribed by Rev"
        let verdict = RewriteOutputContract.validate(input, level: .polish)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "Meeting notes from today.")
        #expect(violations.contains(where: { if case .attribution = $0 { return true }; return false }))
    }

    @Test("Detects 'Generated by' attribution")
    func detectsGeneratedByAttribution() {
        let input = "Some content here.\nGenerated by ChatGPT"
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(_, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(violations.contains(where: { if case .attribution = $0 { return true }; return false }))
    }

    // MARK: - Meta commentary detection

    @Test("Detects 'Thinking:' meta commentary")
    func detectsThinkingMeta() {
        let input = "Thinking: I need to clean this up.\nThe actual cleaned text here."
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "The actual cleaned text here.")
        #expect(violations.contains(where: { if case .metaCommentary = $0 { return true }; return false }))
    }

    @Test("Detects 'Note:' meta commentary")
    func detectsNoteMeta() {
        let input = "The text is clean now.\nNote: I removed some filler words."
        let verdict = RewriteOutputContract.validate(input, level: .polish)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "The text is clean now.")
        #expect(violations.contains(where: { if case .metaCommentary = $0 { return true }; return false }))
    }

    // MARK: - Combined violations

    @Test("Detects preamble + attribution simultaneously")
    func detectsCombinedViolations() {
        let input = "Here's the cleaned version:\nI went to the store.\nTranscribed by otter.ai"
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .repaired(let text, let violations) = verdict else {
            Issue.record("Expected repaired, got \(verdict)")
            return
        }
        #expect(text == "I went to the store.")
        #expect(violations.count == 2)
    }

    // MARK: - Rejection

    @Test("Rejects when entire output is a preamble with no content")
    func rejectsAllPreamble() {
        let input = "Here's the cleaned version:"
        let verdict = RewriteOutputContract.validate(input, level: .clean)
        guard case .rejected = verdict else {
            Issue.record("Expected rejected, got \(verdict)")
            return
        }
    }

    @Test("Rejects empty output")
    func rejectsEmpty() {
        let verdict = RewriteOutputContract.validate("", level: .clean)
        guard case .rejected = verdict else {
            Issue.record("Expected rejected, got \(verdict)")
            return
        }
    }

    @Test("Rejects whitespace-only output")
    func rejectsWhitespace() {
        let verdict = RewriteOutputContract.validate("   \n\n  ", level: .polish)
        guard case .rejected = verdict else {
            Issue.record("Expected rejected, got \(verdict)")
            return
        }
    }

    // MARK: - False positive guards

    @Test("Does not flag 'here' in normal sentence")
    func noFalsePositiveHere() {
        let output = "Here we go again with another meeting."
        let verdict = RewriteOutputContract.validate(output, level: .clean)
        #expect(verdict == .accepted(output))
    }

    @Test("Does not flag 'note' in normal sentence")
    func noFalsePositiveNote() {
        let output = "Please note that the deadline has changed."
        let verdict = RewriteOutputContract.validate(output, level: .clean)
        #expect(verdict == .accepted(output))
    }

    @Test("Does not flag 'sure' in normal sentence")
    func noFalsePositiveSure() {
        let output = "I'm not sure about the timeline."
        let verdict = RewriteOutputContract.validate(output, level: .polish)
        #expect(verdict == .accepted(output))
    }

    @Test("Does not flag 'generated' in middle of text")
    func noFalsePositiveGenerated() {
        let output = "The report generated a lot of discussion among the team."
        let verdict = RewriteOutputContract.validate(output, level: .clean)
        #expect(verdict == .accepted(output))
    }
}
