import Testing
import VoxCore
@testable import VoxBenchmarks

@Suite("BenchmarkContracts")
struct BenchmarkContractsTests {
    @Test("Missing contract yields n/a result")
    func test_evaluateContract_returnsNilPassWhenContractMissing() {
        let result = evaluateContract(output: "Clean output", contract: nil)

        #expect(result.pass == nil)
        #expect(result.violations.isEmpty)
    }

    @Test("Boundary checks normalize wrapper characters and preserve multiple violations")
    func test_evaluateContract_normalizesWrappedOutputAndAccumulatesViolations() {
        let contract = OutputContract(
            mustNotStartWith: ["Sure"],
            mustPreserveTerms: ["idempotency"],
            mustNotEndWith: ["Generated by"]
        )
        let output = "\"Sure, let's ship it.\"\n> Generated by Vox"

        let result = evaluateContract(output: output, contract: contract)

        #expect(result.pass == false)
        #expect(result.violations == [
            "starts_with:Sure",
            "ends_with:Generated by",
            "missing_term:idempotency",
        ])
    }

    @Test("Term preservation matches case-insensitively")
    func test_evaluateContract_preservesTermsCaseInsensitively() {
        let contract = OutputContract(
            mustNotStartWith: nil,
            mustPreserveTerms: ["HMAC SHA-256", "X-Stripe-Signature"],
            mustNotEndWith: nil
        )
        let output = "We validate the hmac sha-256 signature from the x-stripe-signature header."

        let result = evaluateContract(output: output, contract: contract)

        #expect(result.pass == true)
        #expect(result.violations.isEmpty)
    }
}

@Suite("BenchmarkRecommendations")
struct BenchmarkRecommendationsTests {
    @Test("Winner prefers full contract compliance when quality target is met")
    func test_selectRecommendationWinner_prefersPerfectContractCompliance() {
        let fastButNonCompliant = ModelLevelSummary(
            model: "fast",
            level: .clean,
            samples: 10,
            errorRate: 0,
            qualityPassRate: 0.99,
            contractPassRate: 0.8,
            nonEmptyRate: 1,
            latency: Distribution(values: [0.5, 0.6]),
            cost: nil
        )
        let compliant = ModelLevelSummary(
            model: "compliant",
            level: .clean,
            samples: 10,
            errorRate: 0,
            qualityPassRate: 0.97,
            contractPassRate: 1.0,
            nonEmptyRate: 1,
            latency: Distribution(values: [0.8, 0.9]),
            cost: nil
        )

        let winner = selectRecommendationWinner(
            from: [fastButNonCompliant, compliant],
            qualityTarget: 0.95
        )

        #expect(winner?.model == "compliant")
    }

    @Test("Fallback path still uses quality as tiebreaker")
    func test_selectRecommendationWinner_fallbackKeepsQualityAsTieBreaker() {
        let highQuality = ModelLevelSummary(
            model: "high-quality",
            level: .polish,
            samples: 10,
            errorRate: 0,
            qualityPassRate: 0.94,
            contractPassRate: 0.95,
            nonEmptyRate: 1,
            latency: Distribution(values: [0.8, 0.9]),
            cost: nil
        )
        let lowerQuality = ModelLevelSummary(
            model: "lower-quality",
            level: .polish,
            samples: 10,
            errorRate: 0,
            qualityPassRate: 0.10,
            contractPassRate: 0.95,
            nonEmptyRate: 1,
            latency: Distribution(values: [0.4, 0.5]),
            cost: nil
        )

        let winner = selectRecommendationWinner(
            from: [highQuality, lowerQuality],
            qualityTarget: 0.95
        )

        #expect(winner?.model == "high-quality")

        let noPerfectContract = selectRecommendationWinner(
            from: [highQuality],
            qualityTarget: 0.95
        )

        #expect(noPerfectContract?.model == "high-quality")
    }
}
