import Testing
import VoxCore
@testable import VoxPipeline

@Suite("RewritePrompts")
struct RewritePromptsTests {
    @Test("Clean prompt emphasizes paragraph formatting")
    func test_cleanPrompt_emphasizesParagraphFormatting() {
        let prompt = RewritePrompts.prompt(for: .clean)

        #expect(prompt.contains("Be proactive about formatting for readability"))
        #expect(prompt.contains("split into multiple short paragraphs"))
        #expect(prompt.contains("Separate paragraphs with a single blank line"))
    }

    @Test("Clean prompt transcript context includes ASR sizing and formatting guidance")
    func test_cleanPrompt_transcriptContextIncludesASRSizing() {
        let transcript = "this is a test transcript"
        let prompt = RewritePrompts.prompt(for: .clean, transcript: transcript)

        #expect(prompt.contains("ASR CONTEXT (signal only):"))
        #expect(prompt.contains("Transcript size: 25 chars, ~5 words."))
        #expect(prompt.contains("Prioritize sentence boundaries and paragraph breaks for readability"))
    }

    // MARK: - Output contract guardrail regression tests

    private static let outputGuardrailPhrases = [
        "\"Here's ...\" or \"Sure ...\" or \"Of course ...\"",
        "\"Thinking:\" or any meta commentary",
        "\"Transcribed by ...\" or \"Generated by ...\"",
        "quotes, code blocks, or any container markup",
        "No preface, no commentary, no attribution. Do not wrap the entire output in quotes, code blocks, or container markup.",
        "Start with the first word",
        "STT ARTIFACT REMOVAL",
        "Transcribed by Otter.ai",
    ]

    @Test("Clean prompt forbids preface, attribution, meta commentary, and STT artifacts")
    func test_cleanPrompt_forbidsPrefaceAttributionMetaAndSTTArtifacts() {
        let prompt = RewritePrompts.prompt(for: .clean)
        for phrase in Self.outputGuardrailPhrases {
            #expect(prompt.contains(phrase), "Clean prompt missing guardrail: \(phrase)")
        }
    }

    @Test("Polish prompt forbids preface, attribution, meta commentary, and STT artifacts")
    func test_polishPrompt_forbidsPrefaceAttributionMetaAndSTTArtifacts() {
        let prompt = RewritePrompts.prompt(for: .polish)
        for phrase in Self.outputGuardrailPhrases {
            #expect(prompt.contains(phrase), "Polish prompt missing guardrail: \(phrase)")
        }
    }

    @Test("Both prompts share identical output guardrail rules")
    func test_prompts_shareIdenticalGuardrailRules() {
        let clean = RewritePrompts.prompt(for: .clean)
        let polish = RewritePrompts.prompt(for: .polish)

        for phrase in Self.outputGuardrailPhrases {
            #expect(clean.contains(phrase), "Clean prompt missing guardrail: \(phrase)")
            #expect(polish.contains(phrase), "Polish prompt missing guardrail: \(phrase)")
        }
    }
}
