import Testing
import VoxCore
@testable import VoxPipeline

@Suite("RewritePrompts")
struct RewritePromptsTests {
    @Test("Clean prompt emphasizes paragraph formatting")
    func cleanPromptFormattingGuidance() {
        let prompt = RewritePrompts.prompt(for: .clean)

        #expect(prompt.contains("Be proactive about formatting for readability"))
        #expect(prompt.contains("split into multiple short paragraphs"))
        #expect(prompt.contains("Separate paragraphs with a single blank line"))
    }

    @Test("Clean prompt transcript context includes ASR sizing and formatting guidance")
    func cleanPromptTranscriptContext() {
        let transcript = "this is a test transcript"
        let prompt = RewritePrompts.prompt(for: .clean, transcript: transcript)

        #expect(prompt.contains("ASR CONTEXT (signal only):"))
        #expect(prompt.contains("Transcript size: 25 chars, ~5 words."))
        #expect(prompt.contains("Prioritize sentence boundaries and paragraph breaks for readability"))
    }

    // MARK: - Output contract guardrail regression tests

    @Test("Clean prompt forbids preface, attribution, and meta commentary")
    func cleanPromptOutputGuardrails() {
        let prompt = RewritePrompts.prompt(for: .clean)

        // Anti-preamble
        #expect(prompt.contains("\"Here's ...\""))
        #expect(prompt.contains("\"Sure ...\""))
        // Anti-attribution
        #expect(prompt.contains("\"Transcribed by ...\""))
        #expect(prompt.contains("\"Generated by ...\""))
        // Anti-meta
        #expect(prompt.contains("\"Thinking:\""))
        #expect(prompt.contains("meta commentary"))
        // Anti-markup
        #expect(prompt.contains("code blocks"))
        // Anti-STT-artifact
        #expect(prompt.contains("STT ARTIFACT REMOVAL"))
        #expect(prompt.contains("Transcribed by Otter.ai"))
        // Final instruction reinforcement
        #expect(prompt.contains("No preface, no commentary, no attribution"))
        #expect(prompt.contains("Start with the first word"))
    }

    @Test("Polish prompt forbids preface, attribution, and meta commentary")
    func polishPromptOutputGuardrails() {
        let prompt = RewritePrompts.prompt(for: .polish)

        // Anti-preamble
        #expect(prompt.contains("\"Here's ...\""))
        #expect(prompt.contains("\"Sure ...\""))
        // Anti-attribution
        #expect(prompt.contains("\"Transcribed by ...\""))
        #expect(prompt.contains("\"Generated by ...\""))
        // Anti-meta
        #expect(prompt.contains("\"Thinking:\""))
        #expect(prompt.contains("meta commentary"))
        // Anti-markup
        #expect(prompt.contains("code blocks"))
        // Anti-STT-artifact
        #expect(prompt.contains("STT ARTIFACT REMOVAL"))
        #expect(prompt.contains("Transcribed by Otter.ai"))
        // Final instruction reinforcement
        #expect(prompt.contains("No preface, no commentary, no attribution"))
        #expect(prompt.contains("Start with the first word"))
    }

    @Test("Both prompts share identical output guardrail rules")
    func guardrailParity() {
        let clean = RewritePrompts.prompt(for: .clean)
        let polish = RewritePrompts.prompt(for: .polish)

        let guardrailPhrases = [
            "\"Here's ...\" or \"Sure ...\" or \"Of course ...\"",
            "\"Thinking:\" or any meta commentary",
            "\"Transcribed by ...\" or \"Generated by ...\"",
            "quotes, code blocks, or any container markup",
            "No preface, no commentary, no attribution, no quotes",
            "STT ARTIFACT REMOVAL",
            "Transcribed by Otter.ai",
        ]

        for phrase in guardrailPhrases {
            #expect(clean.contains(phrase), "Clean prompt missing guardrail: \(phrase)")
            #expect(polish.contains(phrase), "Polish prompt missing guardrail: \(phrase)")
        }
    }
}
