import Foundation

/// Validates rewrite output for contract violations: preambles, meta commentary,
/// attribution artifacts, and other LLM slop that should never reach the user.
///
/// Returns a verdict with an optional repair. Deterministic — no LLM calls.
public enum RewriteOutputContract {

    public enum Verdict: Equatable, Sendable {
        /// Output passes all checks.
        case accepted(String)
        /// Output had violations that were stripped; repaired text is usable.
        case repaired(String, violations: [Violation])
        /// Output is unsalvageable; caller should fall back to raw transcript.
        case rejected([Violation])
    }

    public enum Violation: Equatable, Sendable, CustomStringConvertible {
        case preamble(String)
        case attribution(String)
        case metaCommentary(String)

        public var description: String {
            switch self {
            case .preamble(let line): return "preamble: \(line)"
            case .attribution(let line): return "attribution: \(line)"
            case .metaCommentary(let line): return "meta: \(line)"
            }
        }
    }

    // MARK: - Preamble patterns

    /// Case-insensitive prefixes that signal the model added a preamble intro.
    private static let preamblePrefixes: [String] = [
        "here's the",
        "here is the",
        "here's your",
        "here is your",
        "sure,",
        "sure!",
        "of course,",
        "of course!",
        "certainly,",
        "certainly!",
        "absolutely,",
        "absolutely!",
        "i've cleaned",
        "i have cleaned",
        "i've rewritten",
        "i have rewritten",
        "i've polished",
        "i have polished",
        "i've edited",
        "i have edited",
        "below is",
        "the following is",
    ]

    // MARK: - Attribution patterns

    /// Known attribution/watermark strings from STT services or models.
    private static let attributionPatterns: [String] = [
        "transcribed by otter",
        "transcribed by rev",
        "transcribed by trint",
        "transcribed by descript",
        "transcribed by sonix",
        "generated by",
        "powered by",
        "made with",
    ]

    // MARK: - Meta commentary patterns

    /// Prefixes that indicate the model is thinking aloud or adding notes.
    private static let metaPrefixes: [String] = [
        "thinking:",
        "note:",
        "[note]",
        "[note:",
        "---",
        "***",
        "editor's note",
        "translator's note",
    ]

    // MARK: - Public API

    public static func validate(_ output: String, level: ProcessingLevel) -> Verdict {
        guard level != .raw else { return .accepted(output) }

        let trimmed = output.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return .rejected([.preamble("empty output")]) }

        var violations: [Violation] = []
        var lines = trimmed.components(separatedBy: .newlines)

        // Check for preamble on first non-empty line
        if let firstIdx = lines.firstIndex(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) {
            let firstLine = lines[firstIdx].trimmingCharacters(in: .whitespaces)
            let lower = firstLine.lowercased()

            for prefix in preamblePrefixes {
                if lower.hasPrefix(prefix) {
                    violations.append(.preamble(firstLine))
                    lines.remove(at: firstIdx)
                    break
                }
            }
        }

        // Check for attribution on last non-empty line
        if let lastIdx = lines.lastIndex(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) {
            let lastLine = lines[lastIdx].trimmingCharacters(in: .whitespaces)
            let lower = lastLine.lowercased()

            for pattern in attributionPatterns {
                if lower.contains(pattern) {
                    violations.append(.attribution(lastLine))
                    lines.remove(at: lastIdx)
                    break
                }
            }
        }

        // Check for meta commentary lines (scan all remaining)
        var metaIndices: [Int] = []
        for (idx, line) in lines.enumerated() {
            let stripped = line.trimmingCharacters(in: .whitespaces)
            let lower = stripped.lowercased()

            for prefix in metaPrefixes {
                if lower.hasPrefix(prefix) {
                    violations.append(.metaCommentary(stripped))
                    metaIndices.append(idx)
                    break
                }
            }
        }
        for idx in metaIndices.reversed() {
            lines.remove(at: idx)
        }

        guard !violations.isEmpty else { return .accepted(trimmed) }

        let repaired = lines
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        if repaired.isEmpty {
            return .rejected(violations)
        }

        return .repaired(repaired, violations: violations)
    }
}
