# Cerberus AI Code Review Council
# https://github.com/misty-step/cerberus
# Fork PR security: repository secrets are unavailable to forks.
# Keep review job gated to same-repo PRs to avoid secret access attempts.
name: Cerberus Council

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: cerberus-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: "${{ matrix.reviewer }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { reviewer: APOLLO, perspective: correctness }
          - { reviewer: ATHENA, perspective: architecture }
          - { reviewer: SENTINEL, perspective: security }
          - { reviewer: VULCAN, perspective: performance }
          - { reviewer: ARTEMIS, perspective: maintainability }
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: misty-step/cerberus@v1
        with:
          perspective: ${{ matrix.perspective }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          timeout: '600'

  verdict:
    name: "Council Verdict"
    needs: review
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: misty-step/cerberus/verdict@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
